abbr_to_region = {
    "NC": "North Carolina",
    "SE": "Sweden",
    "UK": "United Kingdom",
    "PL": "Poland",
    "IL": "Illinois",
    "VT": "Vermont",
    "SD": "South Dakota",
    "MN": "Minnesota",
    "CA": "California",
    "QC": "Quebec",
    "VA": "Virginia",
    "OH": "Ohio",
    "OR": "Oregon",
    "WA": "Washington",
    "AB": "Alberta",
    "NJ": "New Jersey",
    "ON": "Ontario",
    "MA": "Massachusetts",
    "ME": "Maine",
    "BC": "British Columbia",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "AZ": "Arizona",
    "DC": "District of Columbia",
    "NY": "New York",
    "IA": "Iowa",
    "CO": "Colorado",
    "MT": "Montana",
    "PA": "Pennsylvania",
    "NV": "Nevada",
    "IN": "Indiana",
    "KY": "Kentucky",
    "RI": "Rhode Island",
    "NB": "New Brunswick",
    "NL": "Newfoundland and Labrador",
    "AK": "Alaska",
    "TN": "Tennessee",
    "UT": "Utah",
    "OK": "Oklahoma",
    "NE": "Nebraska",
    "MI": "Michigan",
    "WY": "Wyoming",
    "CH": "Switzerland",
    "FR": "France",
    "BE": "Belgium",
    "NL": "Netherlands",
    "DE": "Germany",
    "GR": "Greece",
    "HR": "Croatia",
    "SC": "Scotland",
    "CZ": "Czech",
    "ES": "Spain",
    "PT": "Portugal",
    "FI": "Finland",
    "UA": "Ukraine",
    "RO": "Romania",
    "HU": "Hungary",
    "SI": "Slovenia",
    "RS": "Serbia",
    "JP": "Japan",
    "KR": "South Korea",
    "BA": "Bosnia & Herzegovina",
    "XK": "Kosovo",
    "IE": "Ireland",
    "AT": "Austria",
    "DK": "Denmark",
    "CY": "Cyprus",
    "SK": "Slovakia",
    "LV": "Latvia",
    "LU": "Riga",
    "BIH": "Bosnia",
    "MK": "Macedonia",
    "MAN": "Manitoba"
}
